
#get all todos
# @name getTodos

GET http://localhost:4000/api/todos

###

# @name addTodo
POST http://localhost:4000/api/todos
Content-Type: application/json
{
    "id": 102,
  "todo": "New Todo",
  "completed": false,
  "userId": 100
}

###

# @name patchTodo
PATCH http://localhost:4000/api/todos/102
Content-Type: application/json

{
  "todo": "Patched Todo",
  "completed": true
}

###

# @name updateTodo
PUT http://localhost:4000/api/todos/20
Content-Type: application/json

{
  "todo": "Updated Todo",
  "completed": true,
  "userId": 100
}

###
# @name deleteTodo
DELETE http://localhost:4000/api/todos/5


